apiVersion: v1
kind: Secret
metadata:
  name: service-catalog-secret
type: Opaque
data:
  dsn: cG9zdGdyZXNxbDovL3Jvb3Q6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3NlcnZpY2VfY2F0YWxvZz9zc2xtb2RlPWRpc2FibGU=
  jwt-secret: c2VjcmV0
  db-user: cm9vdA==
  db-password: cGFzc3dvcmQ=
  db-name: c2VydmljZV9jYXRhbG9n